version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      RABBITMQ_HOST: rabbitmq
      QUEUE_NAME: IMAGE-PROCESS
      RESULT_SUFFIX: _result
      ACCESS_TOKEN: TOKEN_FOR_DIRECT_UPLOAD
      UPLOAD_PATH: ./files
    restart: unless-stopped
    depends_on:
      - rabbitmq
  worker:
    build:
      context: ./worker
      dockerfile: ./Dockerfile
    environment:
      FILE_SERVER: http://192.168.0.3:8080
      RABBITMQ_HOST: rabbitmq
      QUEUE_NAME: IMAGE-PROCESS
      RESULT_SUFFIX: _result
      ACCESS_TOKEN: TOKEN_FOR_DIRECT_UPLOAD
      DOWNLOAD_PATH: ./files
    restart: unless-stopped
    depends_on:
      - rabbitmq
  web:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    environment:
      REACT_APP_API_URI: ${API_URI:-127.0.0.1:8080}
    restart: unless-stopped
